language: shell
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
  - echo "ibmcloud $(asdf latest ibmcloud)" >> .tool-versions
  - asdf install
  - export PATH="$HOME/.asdf/shims:$PATH"
script:
  - asdf plugin-add ic-container-service ./
  - asdf list-all ic-container-service
  - asdf plugin-test ic-container-service ./ "ibmcloud plugin list"
os:
  - osx
  - linux
